{% set version = "3.0" %}

package:
  name: savu
  version: {{ version }}

channels:
  - defaults
  - conda-forge
  - astra-toolbox/label/dev
  - ccpi
  - dkazanc

source:
  git_url: ../../

requirements:
  build:
    - python=3.7
  run:
    - python=3.7
    - h5py=2.10.0=mpi_openmpi_*
    - tomopy>1.7
    - scikit-image
    - scipy
    - numpy
    - pandas
    - PyWavelets
    - scikit-learn
    - tomobar
  #  - ccpi-regulariser
  #  - ccpi-reconstruction # but the ccpi downgrades tomopy to 1.4.2
    - i23-seg
    - astra-toolbox
    - pyfai
    - pymca
    - pyfftw
    - xraylib
    - PeakUtils
    - mrcfile
    - tifffile
    - fabio
    - colorama
    - jinja2
    - ipython
    - pytest
    - setuptools
    - mock
    - pip
    # - pip:
    #     - matplotlib
    #     - pyreadline
    #     - pmacparser
    #     - gnureadline==6.3.8
    #     - sphinx-rtd-theme
    #     - nvidia-ml-py3

build:
  preserve_egg_dir: True
  script_env:
    - FACILITY

about:
  home: https://github.com/diamondlightsource/Savu
  license: Apache V2 and GPL V3
  license_file: LICENCE.txt
