name: root
channels:
- defaults
dependencies:
- conda-build
- numpy
- scipy
- colorama
- cython
- ipython
- jinja2
- mock
- pandas
- pep8
- pillow
- pip
- pyqt
- scikit-image
- scikit-learn
- setuptools
- sphinx
- spyder
- sympy
- wheel
- pywavelets
- pytest
- pip:
  - pyreadline
  - appdirs
  - bleach
  - fabio
  - lmfit
  - mako
  - nvidia-ml-py
  - peakutils
  - prompt-toolkit
  - pyfftw
  - pyfai
  - pymca
  - pymca5
  - pytools
  - restview
  - simpleitk
  - sphinx-rtd-theme
  - webencodings


