language: python
python:
  - "2.7"
# before the install
before_install:
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install libcr-dev mpich2 mpich2-doc
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: travis_wait pip install -r requirements.txt --use-mirrors
# command to run tests, e.g. python setup.py test
script:  py.test savu/test
