cache: apt
sudo: true
language: cpp
compiler:
  - gcc
env:
  - OMP_NUM_THREADS=2
#python:
#  - "3.6"
#  - "3.5"
#addons:
#  apt:
#    packages:
#    - libblas-dev
#    - liblapack-dev
#    - gfortran
#    - libhdf5-serial-dev
#    - libboost-all-dev

before_install:
  - cd $TRAVIS_BUILD_DIR/install/3_0_install/savu_v3.0
  - ls -lah

install:
  - ./savu_installer.sh --ci --no_prompts --PREFIX /tmp
# todo don't version lock to 3.0
  - . /tmp/Savu_3.0/miniconda/bin/activate
  - conda list

script:
  - pytest scripts/configurator_tests/ -v
  - pytest savu/test/travis -v --cov savu --cov-report term-missing

after_script:
  - coveralls
  
#allow_failures:
#    - python: "3.5"

