cache: apt
sudo: true
language: cpp
compiler:
  - gcc
env:
  - OMP_NUM_THREADS=2

before_install:
  - cd $TRAVIS_BUILD_DIR/install/3_0_install/savu_v3.0
  - ls -lah

install:
  - ./savu_installer.sh --local --no_prompts --PREFIX /tmp

script:
  - . /tmp/miniconda/bin/activate /tmp/savu
  - path=$(python -c "import savu; import os; print(os.path.abspath(savu.__file__))")
  - savu_path=${path%/savu/__init__.py*}
  - cd $savu_path
  - pytest scripts/configurator_tests/
  - pytest savu/test/travis
  # - pytest savu/test/travis -v --cov savu --cov-report term-missing
