cache: apt
sudo: false
language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - libblas-dev
    - liblapack-dev
    - gfortran
    - libhdf5-serial-dev
    - libcr-dev mpich2 mpich2-doc
    - libboost-all-dev

before_install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION pip numpy scipy h5py pep8 pytest mpi4py scikit-image
  - source activate test-environment 
  - pip install fabio pytest-cov coveralls pyFAI nvidia-ml-py pyfftw
  - python setup.py install

# command to run tests, e.g. python setup.py test
script:
  - py.test savu/test/travis -v --cov savu --cov-report term-missing

after_script:
  - coveralls

