#sudo: false
language: python
python:
  - "2.7_with_system_site_packages"
# before the install
#addons:
#  apt:
#   packages:
#    - libblas-dev
#    - liblapack-dev
#    - gfortran
#    - libhdf5-serial-dev
#    - libcr-dev mpich2 mpich2-doc
#    - libboost-all-dev

before_install:
  - sudo apt-get update
  - sudo apt-get install libblas-dev
  - sudo apt-get install liblapack-dev
  - sudo apt-get install gfortran
  - sudo apt-get install libhdf5-serial-dev
  - sudo apt-get install libcr-dev mpich2 mpich2-doc
  - sudo apt-get install libboost-all-dev
  - sudo apt-get install python-numpy python-scipy
  - sudo apt-get install python-h5py
  - sudo apt-get install python-fabio

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  - travis_wait pip install pep8 --use-mirrors -q
  - travis_wait pip install pytest --use-mirrors -q
  - travis_wait pip install pytest-cov --use-mirrors -q
  - travis_wait pip install mpi4py --use-mirrors -q
  - travis_wait pip install coveralls --use-mirrors -q
  - travis_wait pip install scikit-image --use-mirrors -q
  - travis_wait pip install pyFAI --use-mirrors -q
  
#  - travis_wait pip install numpy --use-mirrors -q
#  - travis_wait pip install scipy --use-mirrors -q
#  - travis_wait pip install h5py --use-mirrors -q

# command to run tests, e.g. python setup.py test
script:
  - py.test savu/test/travis -v --cov savu --cov-report term-missing

after_script:
  - coveralls
