cache: apt
sudo: true
language: cpp
compiler:
  - gcc
env:
  - OMP_NUM_THREADS=2

before_install:
  - cd $TRAVIS_BUILD_DIR/install/3_0_install/savu_v3.0
  - ls -lah
  - touch ~/.condarc
  - "echo channel_priority: strict >> ~/.condarc"

install:
  - PREFIX=/tmp ./savu_installer.sh --local --no_prompts

script:
  - . /tmp/miniconda/bin/activate /tmp/savu
  - pip install coverage pytest-cov
  - path=$(python -c "import savu; import os; print(os.path.abspath(savu.__file__))")
  - savu_path=${path%/savu/__init__.py*}
  - cd $savu_path
  - pytest scripts/configurator_tests/ --cov=scripts
  - pytest savu/test/travis --cov=savu
  # - pytest savu/test/travis -v --cov savu --cov-report term-missing
