name: test-environment
channels:
  - astra-toolbox
  - conda-forge
dependencies:
  - python=2.7
  - numpy
  - scipy
  - pytest
  - h5py
  - pep8
  - mpi4py 
  - scikit-image==0.14.0
  - astra-toolbox
  - xraylib
  - tomopy==1.5.1
  - mock
  - fabio==0.4.0
  - pytest-cov
  - coveralls
  - pyfai==0.15.0
  - pyfftw
  - colorama
  - pymca
  - ccpi::ccpi-regulariser
  - pip:
    - nvidia-ml-py
    - peakutils
    - gnureadline
    - pmacparser

