name: test-environment
channels:
  - nanshe # for pyfftw
  - astra-toolbox
dependencies:
  - python=2/.7
  - numpy
  - scipy
  - pyfftw
  - pytest
  - h5py
  - pep8
  - pytest
  - mpi4py 
  - scikit-image
  - astra-toolbox
  - pip:
    - fabio 
    - pytest-cov
    - coveralls
    - pyFAI 
    - nvidia-ml-py
    - pyfftw

