{% set version = "1.8.18" %}
{% set filename = "hdf5-1.8.18" %}

package:
  name: hdf5
  version: {{ version }}

source:
  fn: {{ filename }}.tar.bz2
  url: https://support.hdfgroup.org/ftp/HDF5/current18/src/{{ filename }}.tar.gz
  #md5: b060bb137d6bd8accf8f0c4c59d2746d

build:
  number: 100

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)

