name: root
channels:
- local
- defaults
- conda-forge
- ccpi
- dkazanc
- astra-toolbox/label/dev
dependencies:
- cython
- spyder
- scipy
- pytest
- colorama
- setuptools
- jinja2
- numpy
- pandas
- mock
- ipython
- matplotlib
- PyWavelets
- scikit-image
- scikit-learn
- tomobar
- ccpi-regulariser
- ccpi-reconstruction
- i23-seg
- astra-toolbox=1.9.0.dev8
- xraylib
- tomopy
- pyfai
- fabio
- pymca
- tifffile
- pyfftw
- PeakUtils
- pip
- pip:
  - pyreadline
  - nvidia-ml-py
  - pmacparser
  - gnureadline
  - sphinx-rtd-theme

