{% set version = "1.6" %}

package:
  name: astra-toolbox
  version: 1.6

source:
  fn: astra-{{ version }}.tar.bz2
  url: http://www.astra-toolbox.com/files/astra-{{ version }}/astra-{{ version }}.tar.bz2
  sha256: e4dfb782cf2e547264947dd89f8c280b3aa63b7f40010abe6270949577b573d3

requirements:
  build:
    - python
    - numpy
    - cython

build:
  number: 100

about:
  home: http://www.astra-toolbox.com
  license: GPLv3
  summary: 'The ASTRA Toolbox is a Python toolbox of high-performance GPU primitives for 2D and 3D tomography.'

