name: root
channels:
- local
- defaults
- conda-forge
- astra-toolbox/label/dev
- ccpi
- dkazanc
dependencies:
- h5py=2.10.0=mpi_openmpi_py36h8f0990d_2
- cython
- scipy
- numpy
- pandas
- PyWavelets
#- scikit-image # doesn't like something
- scikit-learn
- tomobar
- ccpi-regulariser
- ccpi-reconstruction
- astra-toolbox
- xraylib
#- tomopy # can't seem to resolve some dependency
- pyfai
- pymca
- pyfftw
- PeakUtils
# - i23-seg # no py 3.6 build
- tifffile
- fabio
- jinja2
- spyder
- colorama
- ipython
- matplotlib
- pytest
- setuptools
- mock
- yamllint
- pip:
  - pyreadline
  - nvidia-ml-py
  - pmacparser
  - gnureadline==6.3.8
  - sphinx-rtd-theme

