channels:
  - local
  - defaults
  - conda-forge
  - astra-toolbox/label/dev
  - ccpi
  - dkazanc
dependencies:
  - tomopy
  - scikit-image
  - scipy
  - numpy
  - pandas
  - PyWavelets
  - scikit-learn
  - tomobar
# waiting for 3.7 packages for these two
#  - ccpi-regulariser
#  - ccpi-reconstruction
  - larix
  - astra-toolbox
  - pyfai
  - pymca
  - pyfftw
  - xraylib
  - PeakUtils
  - mrcfile
  - tifffile
  - fabio
  - colorama
  - jinja2
  - ipython
  - pytest
  - setuptools
  - mock
  - pip
  - pip:
      - matplotlib
      - pyreadline
      - pmacparser
      - gnureadline==6.3.8
      - sphinx-rtd-theme
      - nvidia-ml-py3
