channels:
- local
- defaults
- conda-forge
- astra-toolbox/label/dev
- ccpi
- dkazanc
dependencies:
- cython
- scipy
- numpy
- pandas
- PyWavelets
#- scikit-image # doesn't like something
- scikit-learn
- tomobar
- ccpi-regulariser
- ccpi-reconstruction
- astra-toolbox
- xraylib
#- tomopy # can't seem to resolve some dependency
#- pyfai # cuda driver not compatible with 10.1?
- pymca
- pyfftw
- PeakUtils
# - i23-seg # no py 3.6 build
- tifffile
- fabio
- colorama
- jinja2
- ipython
- pytest
- setuptools
- pip
- pip:
  - matplotlib
  - pyreadline
  - pmacparser
  - gnureadline==6.3.8
  - sphinx-rtd-theme
  - nvidia-ml-py
