channels:
  - local
  - defaults
  - anaconda
  - conda-forge
  - astra-toolbox/label/dev
  - ccpi
  - dkazanc
dependencies:
  - tomopy
  - scikit-image
  - cython
  - scipy
  - numpy
  - pandas
  - PyWavelets
  - scikit-learn
  - tomobar
  - ccpi-regulariser
  - ccpi-reconstruction # but the ccpi downgrade tomopy to 1.4.2
  - astra-toolbox
  - pyfai
  - pymca
  - pyfftw
  - xraylib
  - PeakUtils
  - tifffile
  - fabio
  - colorama
  - jinja2
  - ipython
  - pytest
  - setuptools
  - mock
  - pip
  - pip:
      - matplotlib
      - pyreadline
      - pmacparser
      - gnureadline==6.3.8
      - sphinx-rtd-theme
      - nvidia-ml-py

