package:
  name: h5py
  version: 2.5.0

source:
  fn: h5py-2.5.0.tar.gz
  url: https://github.com/h5py/h5py/archive/2.5.0.tar.gz

requirements:
  build:
    - python
    - numpy
    - hdf5
    - cython
    - pkgconfig
    - six

build:
  number: 100

about:
  home: http://www.h5py.org/
  license: New BSD (http://opensource.org/licenses/bsd-license.php)

