{% set version = "3.2.0" %}

package:
  name: xraylib
  version: {{ version }}

source:
  fn: xraylib-{{ version }}.tar.gz
  url: https://github.com/tschoonj/xraylib/archive/xraylib-{{ version }}.tar.gz
  sha256: 4f4ab07f47619fa5458efbcd5ea51cd2c76c11a474ef869432235719c5bcdb41

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy >=0.7.0
    - cython
    - swig
    - autoconf
    - libtool
    - automake

