{% set version = "3.2.0" %}

package:
  name: xraylib
  version: {{ version }}

source:
  fn: xraylib-{{ version }}.tar.gz
  url: https://xraylib.tomschoonjans.eu/xraylib-{{ version }}.tar.gz
  sha256: a734a0ea7b8224918f4e2105a4cf6c63664f257c1940a4c633beedf470d1576b

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - numpy
    - scipy >=0.7.0
    - cython
    - swig
    - autoconf
    - libtool
    - automake

